FROM ubuntu:14.04

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN groupadd -r mysql && useradd -r -g mysql mysql

RUN mkdir /docker-entrypoint-initdb.d
RUN locale-gen en_US.UTF-8  

COPY ./debs/ /debs

RUN { \
echo mysql-community-server mysql-community-server/data-dir select ''; \
echo mysql-community-server mysql-community-server/root-pass password ''; \
echo mysql-community-server mysql-community-server/re-root-pass password ''; \
echo mysql-community-server mysql-community-server/remove-test-db select false; \
} | debconf-set-selections \
&& apt-get update \
&& apt-get install -y apparmor-utils libmecab2 psmisc libaio1 \
&& dpkg -i /debs/mysql-common_5.7.12-1ubuntu14.04_amd64.deb \
&& dpkg -i /debs/mysql-community-client_5.7.12-1ubuntu14.04_amd64.deb \
&& dpkg -i /debs/mysql-client_5.7.12-1ubuntu14.04_amd64.deb \
&& dpkg -i /debs/mysql-community-server_5.7.12-1ubuntu14.04_amd64.deb 

# comment out a few problematic configuration values
# don't reverse lookup hostnames, they are usually another container
RUN sed -Ei 's/^(bind-address|log)/#&/' /etc/mysql/my.cnf \
&& echo 'skip-host-cache\nskip-name-resolve' | awk '{ print } $1 == "[mysqld]" && c == 0 { c = 1; system("cat") }' /etc/mysql/my.cnf > /tmp/my.cnf \
&& mv /tmp/my.cnf /etc/mysql/my.cnf

VOLUME /var/lib/mysql

COPY localdb-run.sh /localdb-run.sh
COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/localdb-run.sh"]

EXPOSE 3306
# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
CMD ["mysqld"]
